# Generated by Django 5.2.1 on 2025-06-09 01:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_drive_link'),
        ('upload_center', '0002_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='subject',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='courses.course'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 9, 1, 40, 15, 3544, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
