# Generated by Django 5.2.1 on 2025-06-11 16:33

import upload_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0003_remove_uploadfile_subject_uploadfile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=upload_center.models.upload_to_course_folder),
        ),
    ]
