# Generated by Django 5.2.1 on 2025-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
