# Generated by Django 5.2.1 on 2025-06-24 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctor_accounts_do_nationa_23a446_idx_and_more'),
        ('quiz', '0005_alter_quizsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='score',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_assignments', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_quizzes', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='answers',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
    ]
