# Generated by Django 5.2.1 on 2025-06-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizquestion_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='assigned_to',
        ),
    ]
