# Generated by Django 5.2.1 on 2025-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='score',
            new_name='total_score',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='final_exam_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='midterm_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='section_exam_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='year_work_score',
            field=models.FloatField(default=0),
        ),
    ]
