# Generated by Django 5.2.1 on 2025-06-12 19:25

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_announcement_image),
        ),
        migrations.AlterField(
            model_name='dash',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.dynamic_image_upload),
        ),
    ]
