# Generated by Django 5.2.1 on 2025-06-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_announcement_image_dash_doctor_and_more'),
        ('dashboard', '0003_dash_doctor_alter_dash_student'),
    ]

    operations = [
    ]
