# Generated by Django 5.2.1 on 2025-06-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctor_structures_alter_student_structure'),
        ('courses', '0008_alter_course_structure_alter_studentcourse_course_and_more'),
        ('dashboard', '0004_merge_20250614_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
