# Generated by Django 5.2.1 on 2025-06-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='structure',
            field=models.ManyToManyField(blank=True, to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='student',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.studentstructure'),
        ),
    ]
