# Generated by Django 5.2.1 on 2025-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_structure_student_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_admin_doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('subject_doctor', 'دكتور مادة'), ('admin_doctor', 'دكتور إداري'), ('teaching_assistant', 'معيد')], default='subject_doctor', max_length=20),
        ),
    ]
