# Generated by Django 5.2.1 on 2025-06-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctor_is_admin_doctor_doctor_role'),
        ('courses', '0002_alter_course_doctor'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='structure',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='DoctorCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.studentstructure')),
            ],
            options={
                'unique_together': {('doctor', 'course', 'structure')},
            },
        ),
    ]
