# Generated by Django 5.2.1 on 2025-06-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctor_structure_alter_doctor_national_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorCourseAssignment',
        ),
    ]
