# Generated by Django 5.2.1 on 2025-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_doctorcourseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sec_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
