# Generated by Django 5.2.1 on 2025-06-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_sec_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sec_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
