# Generated by Django 5.2.1 on 2025-06-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_sec_num'),
        ('structure', '0002_studentstructure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.studentstructure'),
        ),
    ]
