# Generated by Django 5.2.1 on 2025-06-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_structure'),
        ('structure', '0002_studentstructure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='structures',
            field=models.ManyToManyField(blank=True, to='structure.studentstructure'),
        ),
    ]
