# Generated by Django 5.2.1 on 2025-06-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_structures'),
        ('structure', '0002_studentstructure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='doctor_structure', to='structure.studentstructure'),
        ),
        migrations.AlterField(
            model_name='student',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_structure', to='structure.studentstructure'),
        ),
    ]
