# Generated by Django 5.2.1 on 2025-06-22 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctor_structures_alter_student_structure'),
        ('structure', '0002_studentstructure_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['national_id'], name='accounts_do_nationa_23a446_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['national_id'], name='accounts_st_nationa_bcf65f_idx'),
        ),
    ]
