# Generated by Django 5.2.1 on 2025-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctor_accounts_do_nationa_23a446_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='رقم الجلوس'),
        ),
    ]
