# Generated by Django 5.2.1 on 2025-06-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=10)),
                ('slot', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Section', 'Section')], max_length=10)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='structure.studentstructure')),
            ],
        ),
    ]
