# Generated by Django 5.2.1 on 2025-06-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=10)),
                ('lecture_type', models.CharField(choices=[('ALL', 'Lecture for All Sections'), ('SPECIFIC', 'Lecture for Specific Section')], default='SPECIFIC', editable=False, help_text="Automatically set to 'Lecture for All Sections' if section is 'All'", max_length=10)),
                ('student_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='structure.studentstructure')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
