# Generated by Django 5.2.1 on 2025-06-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_delete_scheduleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Section', 'Section')], default='Lecture', editable=False, help_text="Automatically set to 'Lecture' if section is 'All'", max_length=10),
        ),
    ]
