# Generated by Django 5.2.1 on 2025-06-04 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_doctorcourseassignment'),
        ('schedule', '0004_alter_schedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='accounts.doctor'),
        ),
    ]
