# Generated by Django 5.2.1 on 2025-06-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctor_structures_alter_student_structure'),
        ('courses', '0008_alter_course_structure_alter_studentcourse_course_and_more'),
        ('schedule', '0006_alter_schedule_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='accounts.doctor'),
        ),
    ]
