# Generated by Django 5.2.1 on 2025-06-04 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_doctorcourseassignment'),
        ('courses', '0002_alter_course_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'subject_doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
        migrations.CreateModel(
            name='CourseSectionAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'teaching_assistant'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assistants', to='courses.course')),
            ],
        ),
    ]
