# Generated by Django 5.2.1 on 2025-06-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_doctor_coursesectionassistant'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.studentstructure'),
        ),
    ]
