# Generated by Django 5.2.1 on 2025-06-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_structures'),
        ('courses', '0006_remove_course_drive_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'subject_doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.doctor'),
        ),
    ]
