# Generated by Django 5.2.1 on 2025-06-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctor_structures_alter_student_structure'),
        ('courses', '0008_alter_course_structure_alter_studentcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='accounts.student'),
        ),
    ]
