# Generated by Django 5.2.1 on 2025-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DATA', 'Data Sceince'), ('CYBER', 'Cyber Security'), ('AUTOTRONICS', 'Autotronics'), ('MECHATRONICS', 'Mechatronics'), ('GARMENT_MANUFACTURING', 'Garment Manufacturing'), ('CONTROL_SYSTEMS', 'Control Systems')], max_length=25)),
                ('year', models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=6)),
            ],
        ),
    ]
