# Generated by Django 5.2.1 on 2025-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_studentstructure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstructure',
            name='department',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DATA', 'Data Science'), ('CYBER', 'Cyber Security'), ('AUTOTRONICS', 'Autotronics'), ('MECHATRONICS', 'Mechatronics'), ('GARMENT_MANUFACTURING', 'Garment Manufacturing'), ('CONTROL_SYSTEMS', 'Control Systems')], max_length=25),
        ),
        migrations.AlterField(
            model_name='studentstructure',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('summer', 'Summer Course'), ('retake_year', 'Retake Year')], default='passed', max_length=20),
        ),
    ]
