# Generated by Django 5.2.1 on 2025-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_studentstructure_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstructure',
            name='failed_courses_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
