# Generated by Django 5.2.1 on 2025-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_course_remove_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='failed_face_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
