# Generated by Django 5.2.1 on 2025-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_face_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='is_open_for_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
