# Generated by Django 5.2.1 on 2025-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_lecturesession_is_open_for_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='qr_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
