# Generated by Django 5.2.1 on 2025-06-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_codesession_delete_qrcodesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesession',
            name='code',
        ),
        migrations.AddField(
            model_name='codesession',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
